PREFIX qb: <http://purl.org/linked-data/cube#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

SELECT ?obs ?compoProp ?value
WHERE {
  ?obs a qb:Observation .
  {?obs qb:dataset <http://thib.me/ratp/trafic-2011>}
    UNION
  {?obs qb:dataSet <http://thib.me/ratp/trafic-2011>} .

  ?obs ?compoProp ?value .
  FILTER (?compoProp != rdf:type && ?compoProp != qb:dataset && ?compoProp != qb:dataSet)
}
